# Generated by Django 3.2.8 on 2021-11-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportdata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
