# Generated by Django 3.2.8 on 2021-11-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportdata', '0002_delete_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Continent',
        ),
    ]
