# Generated by Django 3.2.8 on 2021-12-12 16:25

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportdata', '0004_continent_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availible_Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('country_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('current_season_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['continent']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country']},
        ),
        migrations.AddField(
            model_name='continent',
            name='featured_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sportdata.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.PROTECT, to='sportdata.continent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='continent',
            name='continent',
            field=models.CharField(max_length=25),
        ),
    ]
